// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllProxyGroups():Promise<Array<main.GroupStatus>>;

export function GetConfigInfo():Promise<main.ConfigDTO>;

export function GetGroups():Promise<Array<main.GroupStatus>>;

export function GetHistory(arg1:string):Promise<Record<string, any>>;

export function GetLogHistory():Promise<Array<main.WebLogEntry>>;

export function GetSelectors():Promise<Array<string>>;

export function GetSetup():Promise<Record<string, any>>;

export function GetStats():Promise<Array<main.StatNode>>;

export function GetStatus():Promise<Record<string, any>>;

export function ManualTrigger():Promise<void>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;

export function SaveSetup(arg1:string,arg2:string):Promise<void>;

export function SetGroupLocked(arg1:string,arg2:boolean):Promise<void>;

export function SwitchNode(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<void>;

export function TogglePause():Promise<boolean>;
